# -*- coding: utf-8 -*-
"""Calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lEvcUsm1g4s7Q2m0RevmjVq35offWnEa
"""

### These all notes are made by Gibran Khan Tareen. I have made it for other student's reference and also for my personal revision ###

# Question:
## Write a program that performs the tasks of a simple calculator. 
## The program should first take an integer as input and then based on that integer perform the task as given below:
# 1. If the input is 1, then 2 integers are taken from the user and their sum is printed.
# 2. If the input is 2, then 2 integers are taken from the user and their difference(1st number - 2nd number) is printed.
# 3. If the input is 3, then 2 integers are taken from the user and their product is printed.
# 4. If the input is 4, then 2 integers are taken from the user and the quotient obtained (on dividing 1st number by 2nd number) is printed.
# 5. If the input is 5, then 2 integers are taken from the user and their remainder(1st number mod 2nd number) is printed.
# 6. If the input is 6, then the program exits.
# 7. For any other input, then print "Invalid Operation".
# Note: Each answer in next line.

# Input format : Take integers as input, in accordance to the description of the question. Integer N
# Output format : The output lines must be as prescribed in the description of the question.

# Sample Input: 3
#               1
#               2
#               4
#               4
#               2
#               1
#               3
#               2
#               7
#               6

# Sample Output: 2
#                2
#                5
#                Invalid Operation

def calculator():
    operation = int(input())

    if operation == 1:
        num1 = int(input())
        num2 = int(input())
        print(num1 + num2)
    elif operation == 2:
        num1 = int(input())
        num2 = int(input())
        print(num1 - num2)
    elif operation == 3:
        num1 = int(input())
        num2 = int(input())
        print(num1 * num2)
    elif operation == 4:
        num1 = int(input())
        num2 = int(input())
        print(num1 // num2)
    elif operation == 5:
        num1 = int(input())
        num2 = int(input())
        print(num1 % num2)
    elif operation == 6:
        exit()
    else:
        print('Invalid Operation')


calculator()

# HENCE DONE