# -*- coding: utf-8 -*-
"""Reverse of a Number.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V4z_P1_cnOh0UdRtuXtaSMkHKZCq7E_S
"""

### These all notes are made by Gibran Khan Tareen. I have made it for other student's reference and also for my personal revision ###

# Question:
## Write a program to generate the reverse of a given number N. Print the corresponding reverse number.
## Note : If a number has trailing zeros, then its reverse will not include them. For e.g., reverse of 10400 will be 401 instead of 00401

# Input format : Integer N
# Output format : Corresponding reverse number

# Sample Input 1: 1234
# Sample Output 1: 4321

def reverse_number(N):
    reverse = 0
    while N != 0:
        last_digit = N % 10
        reverse = (reverse * 10) + last_digit
        N = N // 10
    return reverse


N = int(input())
print(reverse_number(N))

# HENCE DONE